name: CI

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: macos-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.14"
          cache: "pip"
          
      - name: Run clean build
        run: python3 -m pip install --upgrade gitpython && python3 ./run_clean_build.py


      - name: Upload reports
        uses: actions/upload-artifact@v7
        with:
          name: reports_index.html
          path: reports/index.html
          archive: false

      - name: Upload reports
        uses: actions/upload-artifact@v7
        with:
          name: reports
          path: reports/

      - name: Upload doc
        uses: actions/upload-artifact@v7
        with:
          name: doc
          path: doc/

      - name: Upload dist
        uses: actions/upload-artifact@v7
        with:
          name: packages
          path: dist/
